### PR TITLE
Add JEI bridge

### PR DESCRIPTION
**Pull request by Abbie5**
Marking as draft as it currently doesn't seem to relocate/inject API classes properly, help would be appreciated :)

### CODE REVIEW

**Comment by Su5eD** [comment]
Sure, I can have a look at that part. Is there anything else required to bridge the APIs?

**Comment by Abbie5** [comment]
No I checked those are the only classes exclusive to the JEI Fabric API (https://github.com/mezz/JustEnoughItems/tree/1.20/FabricApi/src/main/java/mezz/jei/api/fabric)

**Comment by Abbie5** [comment]
Ah I may have misunderstood, I tested this and the plugin loading worked fine, the only issue was the JEI Fabric API classes not being loaded with log messages such as `java.lang.ClassNotFoundException: mezz.jei.api.fabric.constants.FabricTypes`

**Comment by Su5eD** [comment]
The relocation code can be safely removed. JEI puts its fabric-specific classes in a unique `mezz.jei.api.fabric` package, which doesn't exist on the forge version, and therefore it won't cause issues unlike the emi bridge.

**Comment by Abbie5** [comment]
Ah that's a relief

**Review by Su5eD — APPROVED** [review]

**Pull request merged**
